# Generated by Django 4.2.8 on 2026-01-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RFP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.JSONField(default=dict)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent to Vendors"),
                            ("CLOSED", "Closed"),
                            ("AWARDED", "Awarded"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("selected_vendors", models.JSONField(default=list)),
                (
                    "awarded_vendor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("natural_language_input", models.TextField(blank=True)),
            ],
            options={
                "db_table": "rfps",
            },
        ),
        migrations.CreateModel(
            name="RFPField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfp_id", models.CharField(max_length=255)),
                ("field_name", models.CharField(max_length=255)),
                ("field_value", models.TextField()),
                ("field_type", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "rfp_fields",
            },
        ),
    ]
