# Generated by Django 4.2.8 on 2026-01-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfp_id", models.CharField(max_length=255)),
                ("vendor_id", models.CharField(max_length=255)),
                ("vendor_name", models.CharField(max_length=255)),
                ("proposal_content", models.TextField()),
                ("parsed_data", models.JSONField(default=dict)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("delivery_time", models.CharField(blank=True, max_length=255)),
                ("warranty", models.CharField(blank=True, max_length=255)),
                ("payment_terms", models.CharField(blank=True, max_length=255)),
                ("score", models.FloatField(blank=True, null=True)),
                ("evaluation", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_message_id", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PARSED", "Parsed"),
                            ("EVALUATED", "Evaluated"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "proposals",
            },
        ),
    ]
