# Generated by Django 4.2.8 on 2026-01-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PARSED', 'Parsed'), ('ACCEPTED', 'Accepted')], default='RECEIVED', max_length=20),
        ),
    ]
